name:                haskellml
version:             0.1.0.0
github:              "abs-zero/haskellml"
license:             BSD3
author:              "Pratik Chaudhary"
maintainer:          "chaudharypratik97@gmail.com"
copyright:           "2018 Pratik Chaudhary"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, haskellml
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskellml#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- statistics
- vector

library:
  source-dirs: src

executables:
  haskellml-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellml

tests:
  haskellml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellml
